import { CSS_TO_THEME, THEME_TO_CSS, hexToRgb } from './color-utils'

// ---------------------------------------------------------------------------
// Parse
// ---------------------------------------------------------------------------

/**
 * Parses a Windows .theme file (or raw `[Control Panel\Colors]` INI section)
 * and returns a map of CSS variable names → hex color strings.
 */
export function parseThemeFile(content: string): Record<string, string> {
  const colors: Record<string, string> = {}

  // Extract lines from [Control Panel\Colors] section, or treat whole input as INI lines
  const colorsSection = extractColorsSection(content)
  const lines = colorsSection.split('\n')

  for (const line of lines) {
    const match = line.match(
      /^\s*([A-Za-z]+)\s*=\s*((?:[1-9]|1\d|2[0-4])?\d|25[0-5])\s+((?:[1-9]|1\d|2[0-4])?\d|25[0-5])\s+((?:[1-9]|1\d|2[0-4])?\d|25[0-5])\s*$/,
    )
    if (!match) continue

    const themeName = match[1]
    const r = Number(match[2])
    const g = Number(match[3])
    const b = Number(match[4])

    const cssName = THEME_TO_CSS[themeName]
    if (cssName) {
      colors[cssName] = `#${[r, g, b].map(c => c.toString(16).padStart(2, '0')).join('')}`
    }
  }

  return colors
}

function extractColorsSection(content: string): string {
  // Try to find [Control Panel\Colors] section
  const sectionMatch = content.match(
    /\[Control Panel\\Colors\]\s*\n([\s\S]*?)(?=\n\s*\[|$)/,
  )
  if (sectionMatch) return sectionMatch[1]

  // Fallback: treat entire content as INI color lines
  return content
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

/** Ordered list of color property names for the .theme file export. */
const EXPORT_ORDER = [
  'ButtonAlternateFace',
  'ButtonDkShadow',
  'ButtonFace',
  'ButtonHilight',
  'ButtonLight',
  'ButtonShadow',
  'ButtonText',
  'ActiveBorder',
  'AppWorkspace',
  'Background',
  'InactiveBorder',
  'Scrollbar',
  'Window',
  'WindowFrame',
  'WindowText',
  'ActiveTitle',
  'GradientActiveTitle',
  'GradientInactiveTitle',
  'InactiveTitle',
  'InactiveTitleText',
  'TitleText',
  'Menu',
  'MenuBar',
  'MenuHilight',
  'MenuText',
  'GrayText',
  'Hilight',
  'HilightText',
  'HotTrackingColor',
  'InfoText',
  'InfoWindow',
]

/**
 * Generates a full Windows .theme file from a CSS variable name → hex color map.
 */
export function exportThemeFile(
  colors: Record<string, string>,
  displayName = 'My Theme',
): string {
  const colorLines = EXPORT_ORDER.map((themeName) => {
    const cssName = THEME_TO_CSS[themeName]
    const hex = cssName ? colors[cssName] : undefined
    if (!hex) return `${themeName}=0 0 0`
    const rgb = hexToRgb(hex)
    return `${themeName}=${rgb.r} ${rgb.g} ${rgb.b}`
  }).join('\n')

  return `; Generated by murasaki-react98 Theme Designer
; Color calculation inspired by winclassic: https://github.com/tpenguinltg/winclassic (MPL 2.0)


[Theme]
DisplayName=${displayName}

[Control Panel\\Colors]
${colorLines}


[Control Panel\\Desktop]
Wallpaper=
TileWallpaper=0
WallpaperStyle=2
Pattern=
ScreenSaveActive=0

[Control Panel\\Desktop\\WindowMetrics]

[Metrics]
IconMetrics=76 0 0 0 75 0 0 0 75 0 0 0 1 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 84 97 104 111 109 97 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
NonclientMetrics=84 1 0 0 1 0 0 0 16 0 0 0 16 0 0 0 18 0 0 0 18 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 188 2 0 0 0 0 0 1 0 0 0 0 84 97 104 111 109 97 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 12 0 0 0 15 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 188 2 0 0 0 0 0 1 0 0 0 0 84 97 104 111 109 97 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 18 0 0 0 18 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 84 97 104 111 109 97 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 84 97 104 111 109 97 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 84 97 104 111 109 97 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[MasterThemeSelector]
MTSM=DABJDKT
ThemeColorBPP=4



[VisualStyles]
Path=
ColorStyle=@themeui.dll,-854
Size=@themeui.dll,-2019
Transparency=0
ColorizationColor=0XEC0A246A
Composition=0
VisualStyleVersion=10

[boot]
SCRNSAVE.EXE=
`
}

// ---------------------------------------------------------------------------
// File Download
// ---------------------------------------------------------------------------

export function downloadThemeFile(content: string, filename = 'theme.theme'): void {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ---------------------------------------------------------------------------
// File Read Helper
// ---------------------------------------------------------------------------

export function readFileAsText(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(reader.result as string)
    reader.onerror = () => reject(reader.error)
    reader.readAsText(file)
  })
}
